### PR TITLE
Add Featurespace

### PR DESCRIPTION
**Pull request by DrBloke**
Please review our [Contribution Guidelines](https://github.com/lpil/elm-companies/blob/master/CONTRIBUTING.md) to ensure your changes abides by it.

Review your changes and complete the checklist below.

- [x] Company name
- [x] Company description
- [ ] Company location
- [x] GitHub link
- [x] Sorted alphabetically
- [x] Lines wrapped at 80 chars

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
Awesome addition @DrBloke 🎉 

They have GitHub: https://github.com/Featurespace but no `public` repos at the time of writing.
image

Location appears to be Cambridge, UK: https://www.featurespace.com/contact-us
image

They have offices in Atlanta, GA (USA), London and Singapore.

**Comment by DrBloke** [comment]
Thanks @nelsonic. Yes our main office is in Cambridge, UK where all our UI/Elm developers are based, but yes we do have offices in Atlanta, London, Singapore and Israel. I left locations off to save space. And yes, we have no public code repositories at the moment, although we are starting to produce some open-source Elm packages.

**Comment by nelsonic** [comment]
@DrBloke makes sense. 👍 
Maybe include the GitHub link for future reference then if there will be open source packages soon. 💭

**Comment by DrBloke** [comment]
Added GitHub account and a link to Elm Europe talk about Featurespace's experience of adopting Elm

**Review by nelsonic — APPROVED** [review]
@DrBloke nice one. :shipit:

**Pull request merged**
