### PR TITLE
Add Corvus Insurance to Insurance (InsurTech)  section

### PR DESCRIPTION
**Pull request by alenards**
Please review our [Contribution Guidelines](https://github.com/lpil/elm-companies/blob/master/CONTRIBUTING.md) to ensure your changes abides by it.

Review your changes and complete the checklist below.

- [x] Company name - Corvus Insurance
- [x] Company description - inspired by website
- [x] Company location - Boston, Austin + remote
- [x] GitHub link
- [x] Sorted alphabetically
- [x] Lines wrapped at 80 chars

### CODE REVIEW

**Review by nelsonic — APPROVED** [review]
Nice addition @alenards 👍

**Comment by alenards** [comment]
@nelsonic Thanks!

**Comment by nelsonic** [comment]
@alenards worth adding to https://github.com/beam-community/elixir-companies too. 💭

**Comment by alenards** [comment]
> @alenards worth adding to https://github.com/beam-community/elixir-companies too. 💭

I just realized that we're already listed there:
https://elixir-companies.com/en/companies?_target[]=search&_target[]=industry_id&search[industry_id]=68&search[text]=

**Pull request merged**
