### PR TITLE
Remove Knipster

### PR DESCRIPTION
**Pull request by pietro909**
NA

### CODE REVIEW

**Comment by lpil** [comment]
Hi @pietro909 , I'm not sure your PR worked?

**Comment by pietro909** [comment]
It was merged and it's in the page. We see it probably because I need to rebase. There should be an option for that under "merge".

**Comment by lpil** [comment]
Your PR adds another entry for the company and then removes it, leaving the original one. Please update the PR

**Comment by pietro909** [comment]
> Your PR adds another entry for the company and then removes it, leaving the original one. Please update the PR

A plain rebase fixed it.

**Comment by lpil** [comment]
A rebase of your branch to bring it up to date with master will fix it, but I do not have write access to your branch.

If I squash your commits I get an empty commit.

**Comment by pietro909** [comment]
I did it already, please check the diff.

**Pull request merged**
